#include "DedispersionDataAnalysisOutput.h"
#include "DedispersionDataAnalysis.h"
#include <QtCore/QFile>
#include <QtCore/QTextStream>
#include "pelican/utility/ConfigNode.h"
#include "pelican/data/DataBlob.h"
#include <cstring>
#include <iostream>

namespace pelican {

namespace lofar {


/**
 *@details DedispersionDataAnalysisOutput 
 */
DedispersionDataAnalysisOutput::DedispersionDataAnalysisOutput( const ConfigNode& configNode )
    : AbstractOutputStream(configNode)
{
    QString filename = configNode.getOption("file", "name");
    // initialise file connections
    if( filename != "" )
    {
        addFile( filename );
    }
    // MJD of 1/1/11 is 55562
    struct tm tm;
    if ( strptime("2011-1-1 1:0:0", "%Y-%m-%d %H:%M:%S", &tm) != NULL ){
        _epoch = mktime(&tm);
    }
    else {
        throw( QString("SigprocStokesWriter: unable to set epoch.") );
    }
}

/**
 *@details
 */
DedispersionDataAnalysisOutput::~DedispersionDataAnalysisOutput()
{
    foreach( QTextStream* stream, _streams) {
        stream->flush();
        delete stream;
    }
    foreach( QIODevice* device, _devices ) {
        delete device;
    }
}

void DedispersionDataAnalysisOutput::addFile(const QString& filename)
{
    QFile* file = new QFile(filename);
    if( file->open( QIODevice::WriteOnly ) )
    {
         _devices.append( file );
         QTextStream* out = new QTextStream(file);
         _streams.append(out);
         *out << "# Generated by DedispersionDataAnalysisOutput\n"
              << "# Events\n"
              << "# ------\n"
              << "# Time|Dm|Amplitude\n"
              << "# ------\n";
         out->setRealNumberPrecision( 11 );
         out->flush();
    }
    else {
        std::cerr << "DedispersionDataAnalysisOutput: unable to open file for writing: " << filename.toStdString() << std::endl;
        delete file;
    }
}

void DedispersionDataAnalysisOutput::sendStream(const QString& /*streamName*/, const DataBlob* dataBlob)
{
    if( dataBlob->type() == "DedispersionDataAnalysis" ) {
        const DedispersionDataAnalysis* data = static_cast<const DedispersionDataAnalysis*>(dataBlob);
        foreach( QTextStream* out, _streams ) {
            foreach( const DedispersionEvent& e, data->events() ) {
                double mjdStamp = (e.getTime()-_epoch)/86400 + 55562.0;
                *out << mjdStamp << ", " << e.dm() << ", " << e.amplitude() << "\n";
            }
            out->flush();
        }
    }
}

} // namespace lofar
} // namespace pelican
